# Generated by Django 3.2.25 on 2025-06-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Certified Pre-Owned', 'Certified Pre-Owned')], default='Used', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Mileage in kilometers', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_email',
            field=models.EmailField(blank=True, help_text="Owner's contact email", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_phone',
            field=models.CharField(blank=True, help_text="Owner's contact phone number", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Automatic', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
